apiVersion: v1
kind: Service
metadata: 
  #instead of directly defining values, you give placeholders 
  name: {{ . Values.service.name }}
spec: 
  selector:
    app: {{ .Values.service.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}