
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-file
data:
  #these are the contents of the file, would be displayed exactly like this - each one needs to be on own line
  mosquitto.conf: |
    log_dest stdout
    log_type all
    log_timestamp true
    listener 9001

#can separate configurations using three dashes
#handy for kubernetes where you have multiple components for once service and want to put them in one yaml file
---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret-file
type: Opaque
data:
  mosquitto.conf: |
    log_dest stdout
    log_type all
    log_timestamp true
    listener 9001

